version: '3.5'
services:
  rpi-relay-controller:
    container_name: rpi-relay-controller
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8080
      LOCK_TIMEOUT: 5000
      AVAILABLE_RELAYS: config/available_relays.json
      VAILABLE_LOCKS: config/available_locks.json
      TYPEORM_CONNECTION: sqlite
      TYPEORM_DATABASE: db/db.sqlite
      TYPEORM_ENTITIES: src/database/entities/*.js
      TYPEORM_MIGRATIONS: src/database/migrations/*.js
      TYPEORM_SUBSCRIBERS: src/database/subscribers/*.js
      TYPEORM_ENTITIES_DIR: src/database/entities
      TYPEORM_MIGRATIONS_DIR: src/database/migrations
      TYPEORM_SUBSCRIBERS_DIR: src/database/subscribers
      TYPEORM_LOGGING: 'false'
    expose:
      - 8080
    networks:
      - network-bridge
    command: npm run runtime

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - './nginx:/etc/nginx/conf.d'
      - './pages:/var/www/page'
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
